// Automatically generated by https://github.com/metacursion/gravalax/ @ Sat May 26 2018 12:05:14 GMT+0200 (CEST)
({
      getSampleString : function(component, event, helper) {
          helper.getSampleString(component, event, helper)
      }  
})
