// Automatically generated by https://github.com/metacursion/gravalax/ @ Sat May 26 2018 12:05:14 GMT+0200 (CEST)
({
      getSampleString : function(component, event, helper) {
        component
            .find('FooService')
            ._getSampleString()
            .then(helper.getSampleStringSuccess.bind(null, component, helper))
            .catch(helper.getSampleStringFail.bind(null, component, helper))
      },
      getSampleStringSuccess: function (component, helper, result) {
          
      },
      getSampleStringFail: function (component, helper, errors) {
          
      }  
    })
    