// Automatically generated by https://github.com/metacursion/gravalax/ @ Sat May 26 2018 12:10:12 GMT+0200 (CEST)
({
    _getSampleString : function(component, event, helper) {
        return component.lax.enqueue('c.getSampleString', event.getParam('arguments'))
    }  
  })
  